### ISSUE TITLE
Missing endLine property for range in comment schema?

### ISSUE THREAD

**Issue by estan** [google/git-appraise#61] opened 2016-06-15 16:36 UTC
I just came across this project, looks very interesting!

While browsing the comment schema, I saw that a `range` has a `startLine` but no `endLine`:

https://github.com/google/git-appraise/blob/master/schema/comment.json#L35

Was this an oversight or am I just missing something? (The latter is more likely I think)

**Comment by ojarjur** [comment] 2016-06-16 21:49
Ultimately, the schema should include:

- startLine
- startColumn
- endLine
- endColumn

i.e. it should exactly match the [TextRange protocol buffer message defined by Shipshape](https://github.com/google/shipshape/blob/master/shipshape/proto/textrange.proto)

The only reason the omitted fields haven't been included yet is that the command line UI doesn't support displaying them.

At some point, however, they will be added.

As a meta-point, the schema's just define a foundation for the formats; it's always OK to add additional, optional fields.

**Comment by tcolgate** [comment] 2017-11-22 09:42
Made an attempted start on this in  #83

**Comment by tcolgate** [comment] 2017-12-06 08:24
I think is is closed by the merge of #83

**Comment by ojarjur** [comment] 2017-12-06 17:59
@tcolgate Yes; you are right.

Thanks for the feature work and for pointing out that the issue is fixed.

**Closed by ojarjur** 2017-12-06 17:59 UTC
Labels: enhancement, question
