### ISSUE TITLE
The show command does not display comment status correctly

### ISSUE THREAD

**Issue by jishi9** [google/git-appraise#22] opened 2015-12-23 12:25 UTC
It seems that the show command always displays the status of a comment as `fyi`.

### Steps to reproduce
```
git appraise comment -m 'fyi comment'
git appraise comment -lgtm -m 'lgtm comment'
git appraise comment -nmw -m 'nmw comment'
```

Then running `git appraise show` will show something like:
```
    comment: $SHA
      author: $AUTHOR
      time:   $TIMESTAMP
      status: fyi
      fyi comment

    comment: $SHA
      author: $AUTHOR
      time:   $TIMESTAMP
      status: fyi
      lgtm comment

    comment: $SHA
      author: $AUTHOR
      time:   $TIMESTAMP
      status: fyi
      nmw comment
```

On the other hand `git appraise show -json` displays the correct status (in the `resolved` property):
```
  "comments": [
    {
      "hash": "$SHA",
      "comment": {
        "timestamp": "$TIMESTAMP",
        "author": "$AUTHOR",
        "location": {
          "commit": "$SHA"
        },
        "description": "fyi comment"
      }
    },
    {
      "hash": "$SHA",
      "comment": {
        "timestamp": "$TIMESTAMP",
        "author": "$AUTHOR",
        "location": {
          "commit": "$SHA"
        },
        "description": "lgtm comment"
        "resolved": true
      }
    },
    {
      "hash": "$SHA",
      "comment": {
        "timestamp": "$TIMESTAMP",
        "author": "$AUTHOR",
        "location": {
          "commit": "$SHA"
        },
        "description": "nmw comment"
        "resolved": false
      }
    }
```

**Comment by barbastan** [comment] 2015-12-23 15:37
Interesting!  Omar (our Tech Lead) wrote that code.  *Maaaaybe* he had a
reason.  He'll be back on Jan 4 and will respond.

Thanks!
Barbara

**Comment by hazbo** [comment] 2015-12-23 16:23
The pull request I've just made should fix this bug, @jishi9 does this look reasonable to you?

**Comment by hazbo** [comment] 2015-12-23 17:04
I've just ran through [this process](https://github.com/google/git-appraise/issues/17#issuecomment-166888010) a couple of times since fixing this bug, and it also appears to change the status of the review as a whole.

The discussion we had in that last thread outlined that this wasn't the case. Since changing that code, it now is. At this stage I'm not sure whether or not that is intended. But yeah - just thought I'd mention that.

**Comment by barbastan** [comment] 2015-12-23 18:53
I am eager to hear what Omar originally had in mind.

Thanks again.
Barbara

**Comment by jishi9** [comment] 2015-12-24 00:07
@hazbo 

> It also appears to change the status of the review as a whole. The discussion we had in that last thread outlined that this wasn't the case. Since changing this code, it now is. 

I don't think that's the case, the status of review as a whole was already displayed fine. As far as I could tell the bug only pertained to how the status of individual commits are displayed (always `fyi`, as opposed to `lgtm` or `needs work` where appropriate). Your change does fix this problem.


Looking at [review.go](https://github.com/hazbo/git-appraise/blob/master/review/review.go#L34-L39) where the `CommenThread.Resolved` field is defined, I'm thinking that maybe the [original implementation](https://github.com/hazbo/git-appraise/commit/2a2f0546abd53c701f7e72a8bee44685dc2987e5#diff-9c7a05e4295bdceebccd9558859ab151L124) of `show` was correct in using `thread.Resolved` rather than `comment.Resolve`. The bug might be that the value of `thread.Resolved` is not updated beforehand using [updateResolvedStatus](https://github.com/hazbo/git-appraise/blob/master/review/review.go#L97). I have created pull request #24 to fix this.

====

With this change things started to make more sense. This is the model I have pieced out:

A review's overall status:
- There are no comment-threads, or all comment-thread statuses are FYI => `pending`
- There is at least one LGTM comment-thread, and *no* NMW comment-threads => `accepted`
- There is at least one NMW comment-thread => `rejected`

A comment-thread's overall status (this is a recursive definition):
- root comment is NMW
  - there exists a direct LGTM child && no direct NMW child exists => `FYI`
  - otherwise => `NMW`
- root comment is `LGTM`
  - direct NMW child exists => `NMW`
  - otherwise => `LGTM`
- root comment is `FYI`
  - direct NMW child exists => `NMW`
  - otherwise => `FYI`

N.B. A comment-thread may be a global, attached to a file, or attached to a line.

**Comment by ojarjur** [comment] 2016-01-04 18:35
@jishi9 Yes, your interpretation is exactly what was intended (and your bug fix was a good one). I merged your PR, and it seems to have fixed the bug (from what I've seen) so I'm going to close this issue.

Please re-open it if you find anything seems off.

Also, thanks for digging into this and sending out the fix!

**Closed by ojarjur** 2016-01-04 18:35 UTC
